"""about text column added to profile class

Revision ID: 46ec3ccb2a5e
Revises: b1cde9b9d5ee
Create Date: 2021-09-12 04:07:04.066483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ec3ccb2a5e'
down_revision = 'b1cde9b9d5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('about_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'about_text')
    # ### end Alembic commands ###
