"""Profile class added

Revision ID: 53259453ba78
Revises: 07b1eb34a834
Create Date: 2021-09-12 01:30:01.423277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53259453ba78'
down_revision = '07b1eb34a834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prof_name', sa.String(length=50), nullable=True),
    sa.Column('prof_age', sa.String(length=10), nullable=True),
    sa.Column('prof_phone', sa.String(length=20), nullable=True),
    sa.Column('prof_email', sa.String(length=100), nullable=True),
    sa.Column('prof_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
