"""hello text column added to profile class

Revision ID: 6dfbb32090d1
Revises: 46ec3ccb2a5e
Create Date: 2021-09-12 04:17:45.405048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfbb32090d1'
down_revision = '46ec3ccb2a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('hello_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'hello_text')
    # ### end Alembic commands ###
