"""prof img deleted to profile class

Revision ID: b1cde9b9d5ee
Revises: f66a89d1d8c9
Create Date: 2021-09-12 03:25:23.022108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1cde9b9d5ee'
down_revision = 'f66a89d1d8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'prof_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('prof_img', sa.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###
