"""date column add to projects module

Revision ID: bb91e6a9a8cd
Revises: 6dfbb32090d1
Create Date: 2021-09-14 01:52:28.793004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb91e6a9a8cd'
down_revision = '6dfbb32090d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'date')
    # ### end Alembic commands ###
