"""Education class added.

Revision ID: e037d8173a54
Revises: 2d5d762c96eb
Create Date: 2021-09-14 23:19:14.136595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e037d8173a54'
down_revision = '2d5d762c96eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edu_name', sa.String(length=100), nullable=True),
    sa.Column('edu_start_date', sa.String(length=10), nullable=True),
    sa.Column('edu_finish_date', sa.String(length=10), nullable=True),
    sa.Column('edu_content', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    # ### end Alembic commands ###
