"""Blogs model changed.

Revision ID: f1f2c2264a9f
Revises: 
Create Date: 2021-09-09 22:54:46.771348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f2c2264a9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_dateTime', sa.String(length=70), nullable=True))
    op.drop_column('blogs', 'blog_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_date', sa.DATETIME(), nullable=True))
    op.drop_column('blogs', 'blog_dateTime')
    # ### end Alembic commands ###
